version: '3.8'
services:
  web1:
    build: ./web1
    container_name: web1
  web2:
    build: ./web2
    container_name: web2
  lb:
    build: ./lb
    ports:
      - "8080:80"
    environment:
      BACKEND1: "web1:80"
      BACKEND2: "web2:80"
    depends_on:
      - web1
      - web2
